resolve syntax on line 13

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -10,10 +10,10 @@ jobs:
         run: echo "Hello, world!"
   echo-goodbye:
     runs-on: ubuntu-latest
-      steps:
-        - name: Failed step
-          run: |
-            echo "I will fail"
-            exit 1
-        - name: Say goodbye
-          run: echo "Goodbye!"
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say goodbye
+        run: echo "Goodbye!"
